### ISSUE TITLE
keeping track of the index element output from rdp

### ISSUE THREAD

**Issue by dunguyen84** [fhirschmann/rdp#8]
Hello and thank you for your package.
I am using it for signal processing and having a timestamps on each data. Is there a possibility to recover these timestamp or the index of the data kept once output from the rdp algorithm?

Many thanks

**Comment by fhirschmann** [comment]
Hi @dunguyen84,

Yes, that's possible with the iterative version:

    >>> from rdp import rdp
    >>> import numpy as np
    >>> arr = np.array([1, 1, 2, 2, 3, 3, 4, 4]).reshape(4, 2)
    >>> arr
    array([[1, 1],
           [2, 2],
           [3, 3],
           [4, 4]])
    >>> mask = rdp(arr, algo="iter", return_mask=True)
    >>> mask
    array([ True, False, False,  True], dtype=bool)
    >>> arr[mask]
    array([[1, 1],
           [4, 4]])

**Comment by dunguyen84** [comment]
Thank you very much

**Comment by fhirschmann** [comment]
You're welcome. :)
